Repository jenkins-x-plugins/jx-updatebot, pull requests merged in 2021-06, with the labels that each got.

#21 fix: better version prefix handling
  docs/cmd/jx-updatebot.md
  docs/cmd/jx-updatebot_argo.md
  docs/cmd/jx-updatebot_environment.md
  docs/cmd/jx-updatebot_pipeline.md
  docs/cmd/jx-updatebot_pr.md
  docs/cmd/jx-updatebot_sync.md
  docs/cmd/jx-updatebot_version.md
  docs/config.md
  docs/man/man1/jx-updatebot-argo.1
  go.mod
  go.sum
  pkg/cmd/argo/argo.go
Labels: approved, size/M

#23 docs: fixed GitHub urls for banners
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#24 fix: add command to sync ArgoCD repos
  docs/cmd/jx-updatebot.md
  docs/cmd/jx-updatebot_argo.md
  docs/cmd/jx-updatebot_argo_promote.md
  docs/cmd/jx-updatebot_argo_sync.md
  docs/cmd/jx-updatebot_environment.md
  docs/cmd/jx-updatebot_pipeline.md
  docs/cmd/jx-updatebot_pr.md
  docs/cmd/jx-updatebot_sync.md
  docs/cmd/jx-updatebot_version.md
  docs/config.md
  docs/man/man1/jx-updatebot-argo-promote.1
  docs/man/man1/jx-updatebot-argo-sync.1
  docs/man/man1/jx-updatebot-argo.1
  go.mod
  go.sum
  pkg/argocd/app_filter.go
  pkg/argocd/app_filter_test.go
  pkg/argocd/app_version.go
  pkg/argocd/helpers.go
  pkg/cmd/argo/argo.go
  pkg/cmd/argo/promote/applications.go
  pkg/cmd/argo/promote/applications_test.go
  pkg/cmd/argo/promote/promote.go
  pkg/cmd/argo/promote/test_data/simple/expected/myapp.yaml
  pkg/cmd/argo/promote/test_data/simple/expected/random.yaml
  pkg/cmd/argo/promote/test_data/simple/source/myapp.yaml
  pkg/cmd/argo/promote/test_data/simple/source/random.yaml
  pkg/cmd/argo/sync/repo_details.go
  pkg/cmd/argo/sync/sync.go
  pkg/cmd/argo/sync/sync_test.go
  pkg/cmd/argo/sync/test_data/exclude-app1/expected/app1.yaml
  pkg/cmd/argo/sync/test_data/exclude-app1/expected/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/exclude-app1/source/app1.yaml
  pkg/cmd/argo/sync/test_data/exclude-app1/source/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/exclude-app1/target/app1.yaml
  pkg/cmd/argo/sync/test_data/exclude-app1/target/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/include-app1/expected/app1.yaml
  pkg/cmd/argo/sync/test_data/include-app1/expected/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/include-app1/source/app1.yaml
  pkg/cmd/argo/sync/test_data/include-app1/source/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/include-app1/target/app1.yaml
  pkg/cmd/argo/sync/test_data/include-app1/target/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/simple/expected/app1.yaml
  pkg/cmd/argo/sync/test_data/simple/expected/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/simple/source/app1.yaml
  pkg/cmd/argo/sync/test_data/simple/source/somedir/app2.yaml
  pkg/cmd/argo/sync/test_data/simple/target/app1.yaml
  pkg/cmd/argo/sync/test_data/simple/target/somedir/app2.yaml
  pkg/cmd/environment/environment.go
  pkg/cmd/pr/command.go
  pkg/cmd/root.go
  pkg/cmd/sync/env_details.go
Labels: approved, size/XXL

#26 fix: broken test
  go.mod
  go.sum
  pkg/cmd/pr/pr_test.go
  pkg/cmd/pr/test_data/versionStream/.jx/updatebot.yaml
Labels: approved, size/S
