Repository jenkins-x-plugins/jx-updatebot, pull requests merged in 2022-05, with the labels that each got.

#40 refactor: use T.TempDir to create temporary test directory
  pkg/cmd/argo/promote/applications_test.go
  pkg/cmd/argo/sync/sync_test.go
  pkg/cmd/flux/promote/charts_test.go
  pkg/cmd/flux/sync/sync_test.go
  pkg/cmd/sync/sync_test.go
Labels: ok-to-test, lgtm, size/S

#43 fix: do not overwrite release chart step
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  OWNERS
Labels: size/S

#44 chore: enable codeql alerts
  .github/workflows/codeql-analysis.yml
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/M
