Repository jenkins-x-plugins/jx-updatebot, pull requests merged in 2025-03, with the labels that each got.

#119 fix: use application name when setting commit details
  pkg/cmd/pr/pr.go
Labels: ok-to-test, approved, size/M

#111 fix: use PR author when assigning merge commits
  pkg/cmd/pr/pr.go
  pkg/cmd/pr/pr_test.go
Labels: ok-to-test, approved, size/L

#120 feat: show release notes in pull request body
  pkg/cmd/environment/environment.go
Labels: approved, size/M
